version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: hotel-mongodb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    image: anshushetty/hotelmanagementbackend:latest
    container_name: hotel-management-backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/hotelBooking
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
